### ISSUE TITLE
[Bug]: Vertical Walls Not Flush

### ISSUE THREAD

**Issue by JLUsr** [Fuzss/diagonalwalls#10]
### Mod Loader (Required)

Quilt

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.1.3

### Minimal Setup (Required)

Yes

### Notes (Required)

If you try and build a tall wall all of the wall's below the top row will not connect vertically. This happens even in a minimal setup using Fabric rather than Quilt. (This does not impact the vanilla Minecraft wall blocks that have not been converted to DiagonalWalls blocks)

Vanilla behaviour/Vanilla walls
![2024-07-31_10 52 33](https://github.com/user-attachments/assets/0237fc8d-f7c2-46a5-8ddf-37f0daf415a5)

DiagonalWalls behaviour/DiagonalWalls walls
![2024-07-31_10 58 51](https://github.com/user-attachments/assets/e84da456-9d57-4c7a-a664-769c6e42dd18)

### latest.log (Required)

https://gist.github.com/JLUsr/ceb81782573c335041383fe9a83bfc9e

**Comment by Fuzss** [comment]
That is intentional, the vertical wall block states have been removed to make room for the diagonal block states. That's a technical limitation, the mod page mentions it.

**Comment by SSJ3Bane** [comment]
Everyone seems to be having the same question and getting the same realization...
It's a stupid fix, but, an item to replace the block with the original wall variant?

**Comment by Fuzss** [comment]
Well, I could image that maybe sneak+placing a wall could place the vanilla variant. Or sneak+right clicking a placed wall could convert it. What do you think of that? Maybe even both?

**Comment by Fuzss** [comment]
Just to add to this: In the 1.21+ versions you can use sneak+right click on a placed wall to convert it back to vanilla, so that upwards connections will show again when the walls are not connected diagonally

**Comment by vinnyg0621** [comment]
you can even make tall variants for the diagonal wall too!

**Comment by Azagwen** [comment]
it's been over one year and a half, how is this deal-breaker issue not fixed yet? I think the special block Item path was a good solution, but is there any progress on fixing this?

> Just to add to this: In the 1.21+ versions you can use sneak+right click on a placed wall to convert it back to vanilla, so that upwards connections will show again when the walls are not connected diagonally

This is an interesting temporary fix, but letting you know I had to come here to realize that was even a thing! Maybe a notice elsewhere more visible could be nice.
