### ISSUE TITLE
[Suggestion]: Add way to prevent block from becoming diagonal

### ISSUE THREAD

**Issue by VincentHuto** [Fuzss/diagonalwalls#13]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

There should be a way to place the block in a way it does not become diagonal by default, something like holding a hotkey, I ask because certain mods like Mana and Artifice use Nether brick walls in structures that no longer work due to the automatic conversion, as well as sometimes its nice on structures to not have them connect

**Comment by kieranmogs** [comment]
+1 to this, any multiblock structure that uses fences such as Create: Factory must grow's Blast furnace break because this mod overrides the wall item on placement

**Comment by Fuzss** [comment]
You can sneak+right click to turn it back to vanilla.
