### ISSUE TITLE
[Suggestion]: Connect the walls vertically so there is no gaps

### ISSUE THREAD

**Issue by xXFoundationXx** [Fuzss/diagonalwalls#14]
### Mod Loader (Optional)

⸺

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

it be nice to connect the walls vertically so there is no gaps when they are placed on each other, vanilla leaves no gaps, but adding your mod brings wall gaps back, i if i had to chose  between vanillas no gapped walls or your vertical gapped walls, id choose vanillas just so i dont have those horrible gaps, 

plz consider adding this feature

**Comment by XAgent1990** [comment]
Yes, this is a huge issue.
I would love to have this mod, but the fact they don't connect up seamlessly makes the mod actually be a downgrade to the vanilla mechanic.

**Comment by Fuzss** [comment]
#10

**Comment by xXFoundationXx** [comment]
buddy, regarless if you close this issue, and its due to limitations,, i cant bring myself to use your mod otherwise, as xagent said, its a downgrade, you obsviously dont gatta do anything, its your mod, im just saying, with others like me who feel the same about the gap, i cant download this, and many others will struggle as well to, thats all, if someday you find a way to bypass the limitation for some reason, ill gladly reinstall this as a go to
