### ISSUE TITLE
[Bug]: Vertically stacked walls don't connect

### ISSUE THREAD

**Issue by littlewing1977** [Fuzss/diagonalwalls#18]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.3

### Minimal Setup (Required)

Yes

### Notes (Required)

When placing walls on top of each other, the walls don't connect as they should.  With no mods installed, they connect fine.  Once Diagonal Walls is installed they break.  Walls that were placed before adding the mod stay connected.  

![2024-11-07_11-44-43](https://github.com/user-attachments/assets/7a3bd74c-f6e8-4595-81d4-dec39e6d86d3)

### latest.log (Required)

https://gist.github.com/littlewing1977/b1913a996de750c2517b548bfbe62037

**Comment by Fuzss** [comment]
#10
