### ISSUE TITLE
[Bug]: Walls and fences get placed diagonally

### ISSUE THREAD

**Issue by parheli** [Fuzss/diagonalwalls#19]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.4

### Minimal Setup (Required)

Yes

### Notes (Required)

As stated in the title, all walls and fences get placed with the part that usually connects them diagonally 'sticking out'. Placing blocks near doesn't affect it. My modpack is BigChadGuys Plus (w- Cobblemon!) and I'm playing on a server, other players don't have this issue so it seems to be a visual bug. Launcher is Prism Launcher 9.1

Diagonal Fences is used as well!! v8.1.4

![Base Profile Screenshot 2024 11 19 - 20 46 17 58](https://github.com/user-attachments/assets/fbf81e69-6f9d-46e1-b0c7-fdb9115ace2a)
![Base Profile Screenshot 2024 11 19 - 21 00 06 83](https://github.com/user-attachments/assets/7ee10d9f-e88d-4cdd-8893-687cb918efe1)

[latest.log](https://github.com/user-attachments/files/17820573/latest.log)

### latest.log (Required)

[latest.log](https://github.com/user-attachments/files/17820573/latest.log)

**Comment by Fuzss** [comment]
Does this happen with v8.0.3?

**Comment by parheli** [comment]
It does! As you could probably guess, the issue covers not only the walls, but the fences and the windows from your other mods. It also has something to do with the server, in solo world works just fine

**Comment by Fuzss** [comment]
Does it maybe work if you log in to any singleplayer world once (just log in and quit again, no need to do anything else) and then go on the server afterward?

**Comment by parheli** [comment]
Sadly doesn't help

**Comment by parheli** [comment]
small update: i dont think this is a visual bug, i think for my character that extra sticking out part genuinely exists, as i cannot pass through it. it doesnt exist for everyone else though

**Comment by parheli** [comment]
solved: the reason for this and many more other visual bugs was me having a different version of the modpack from the server, i had 2.11.1 when needed 2.10.1. my bad
