### ISSUE TITLE
[Bug]: Incompatibility with Dimensional Dungeons

### ISSUE THREAD

**Issue by Sereliana** [Fuzss/diagonalwalls#2]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.2

### Minimal Setup (Required)

No

### Notes (Required)

Current behaviour: Placing the Portal Crown blocks from Dimensional Dungeons seems to turn them into different blocks that the portal doesn't recognize, meaning you can't progress in the mod. It would be great if the block could be excluded.

Steps to reproduce: 1. Build the advanced portal frame 2. Use an Advanced Dungeon Key to activate the portal 3. The portal will tell you that it's missing crown blocks.

### latest.log (Required)

https://gist.github.com/Sereliana/e82f8b8f0661568238a3fffc0d44921e

**Comment by Sereliana** [comment]
Well I went to sleep and was apparently only capable of reading the description after getting up. My bad! I'll figure out how to add the block tag.

**Comment by Fuzss** [comment]
If you find the problematic wall ids feel free to post those here so they can be included by default!

**Comment by Sereliana** [comment]
It's diagonalwalls:dimdungeons/block_portal_crown, or rather dimdungeons:block_portal_crown. Though I wrote the dum dungeons dev on their discord and he might add the diagonal walls one to work with the portal instead!

**Comment by Fuzss** [comment]
If they for their portal creation check a block tag containing `dimdungeons:block_portal_crown` instead of having a hardcoded check for the `dimdungeons:block_portal_crown` block this can easily made to work with Diagonal Walls, since the diagonal blocks inherit all block tags from the original.
