### ISSUE TITLE
[Bug]: Walls don't connect vertically properly

### ISSUE THREAD

**Issue by HaydnVH** [Fuzss/diagonalwalls#3]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.2

### Minimal Setup (Required)

Yes

### Notes (Required)

Walls do not properly connect to blocks above them.  With the mod installed:
![image](https://github.com/Fuzss/diagonalwalls/assets/11154439/8695a091-461c-49f8-b731-9a18ad03ff43)
Vanilla behaviour:
![image](https://github.com/Fuzss/diagonalwalls/assets/11154439/eae8d39f-d0a7-4794-b142-6418c891c02c)

### latest.log (Required)

https://gist.github.com/HaydnVH/7c8c2e075f86bc4a513ee74d434d1068

**Comment by HaydnVH** [comment]
Sorry, forgot to RTFM and didn't realize that this has already been addressed.  Feel free to close if this can't be fixed.

**Comment by vinnyg0621** [comment]
wait, what?! i saw this too and i was gonna report. oh, well... wait, it can't be fixed?!?! 😭😭😭
