### ISSUE TITLE
[Bug]: Stacked Walls Not Rendering Flush

### ISSUE THREAD

**Issue by StitchLockwood** [Fuzss/diagonalwalls#9]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

[FABRIC] [1.20.1] DiagonalWalls-v8.0.3

### Minimal Setup (Required)

Yes

### Notes (Required)

When you place multiple layers of wall on top of each other they leave gaps in between the layers.

My world:
![2024-07-28_18 34 03](https://github.com/user-attachments/assets/8b95159a-ce7d-4618-95e7-7b97510d36f9)

Minimal Setup:
![2024-07-28_18 40 36](https://github.com/user-attachments/assets/63a54fb3-f00c-4b4b-8cbf-cc3b168e3af8)

Vanilla Minecraft 1.20.1:
![2024-07-28_18 46 05](https://github.com/user-attachments/assets/ea5feb2c-41c6-4bd9-9de1-cb854c267c9a)

### latest.log (Required)

https://gist.github.com/StitchLockwood/7f34f9fd36af43189a5cb8a3f3c5a74c

**Comment by Fuzss** [comment]
Thanks, that's intentional. Diagonal block states + upwards connection block states would be too much for the game to handle.
